import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>HotelX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Home Page</h1>

    </div>
  )
}